version: '2'
# update
services:
  cache:
    image: memcached:alpine
    ports:
      - "11211:11211"
  flask-app:
    build: .
    container_name: flask-bridge-app
    ports:
      - "8000:8000"
    volumes:
      - C:\Users\majta\Pictures\dbFlask:/app/data
    depends_on:
      - cache
    environment:
      - MEMCACHED_HOST=cache
    restart: always
    
