version: '3'
services:
  flask-app:                      # The name of your service in Container Station
    image: capydev/flask-app:latest # TELLS QNAP: "Go to Docker Hub and get the latest code I pushed"
    ports:
      - "8000:8000"               # TELLS QNAP: "Open port 8000 on the NAS so I can see the website"
    volumes:
      - /share/Public/flask_data:/app/data # THE BIND MOUNT: Links your NAS folder to the app's folder
    restart: always